runtime: python39  # Use Python 3.9 runtime

entrypoint: gunicorn -b :$PORT app:app  # Entry point for your application

handlers:
- url: /static
  static_dir: static  # Serve static files from the "static" directory
- url: /.*
  script: auto  # Route all other URLs to the application
service: default
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5
env_variables:
  AWS_ACCESS_KEY_ID: AKIAUSJEUQFB77FEFEA6
  AWS_SECRET_ACCESS_KEY: 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
  S3_BUCKET_NAME: umkc-images

